/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const UpgradeFormLazyRouteImport = createFileRoute('/upgrade-form')()
const TestToggleLazyRouteImport = createFileRoute('/test-toggle')()
const TestStateMachineLazyRouteImport = createFileRoute('/test-state-machine')()
const TestSlotLazyRouteImport = createFileRoute('/test-slot')()
const TestPrimitiveLazyRouteImport = createFileRoute('/test-primitive')()
const TestFormLazyRouteImport = createFileRoute('/test-form')()
const TestComposeRefsLazyRouteImport = createFileRoute('/test-compose-refs')()
const TestLazyRouteImport = createFileRoute('/test')()
const RefExampleLazyRouteImport = createFileRoute('/ref-example')()
const RawHtmlWithCssLazyRouteImport = createFileRoute('/raw-html-with-css')()
const OverflowLazyRouteImport = createFileRoute('/overflow')()
const NavigationLazyRouteImport = createFileRoute('/navigation')()
const Layout1LazyRouteImport = createFileRoute('/layout1')()
const IndexPageLazyRouteImport = createFileRoute('/index-page')()
const Flow2LazyRouteImport = createFileRoute('/flow2')()
const Flow1LazyRouteImport = createFileRoute('/flow1')()
const AboutLazyRouteImport = createFileRoute('/about')()

const UpgradeFormLazyRoute = UpgradeFormLazyRouteImport.update({
  id: '/upgrade-form',
  path: '/upgrade-form',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/upgrade-form.lazy').then((d) => d.Route))
const TestToggleLazyRoute = TestToggleLazyRouteImport.update({
  id: '/test-toggle',
  path: '/test-toggle',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/test-toggle.lazy').then((d) => d.Route))
const TestStateMachineLazyRoute = TestStateMachineLazyRouteImport.update({
  id: '/test-state-machine',
  path: '/test-state-machine',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/test-state-machine.lazy').then((d) => d.Route),
)
const TestSlotLazyRoute = TestSlotLazyRouteImport.update({
  id: '/test-slot',
  path: '/test-slot',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/test-slot.lazy').then((d) => d.Route))
const TestPrimitiveLazyRoute = TestPrimitiveLazyRouteImport.update({
  id: '/test-primitive',
  path: '/test-primitive',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/test-primitive.lazy').then((d) => d.Route),
)
const TestFormLazyRoute = TestFormLazyRouteImport.update({
  id: '/test-form',
  path: '/test-form',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/test-form.lazy').then((d) => d.Route))
const TestComposeRefsLazyRoute = TestComposeRefsLazyRouteImport.update({
  id: '/test-compose-refs',
  path: '/test-compose-refs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/test-compose-refs.lazy').then((d) => d.Route),
)
const TestLazyRoute = TestLazyRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/test.lazy').then((d) => d.Route))
const RefExampleLazyRoute = RefExampleLazyRouteImport.update({
  id: '/ref-example',
  path: '/ref-example',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ref-example.lazy').then((d) => d.Route))
const RawHtmlWithCssLazyRoute = RawHtmlWithCssLazyRouteImport.update({
  id: '/raw-html-with-css',
  path: '/raw-html-with-css',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/raw-html-with-css.lazy').then((d) => d.Route),
)
const OverflowLazyRoute = OverflowLazyRouteImport.update({
  id: '/overflow',
  path: '/overflow',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/overflow.lazy').then((d) => d.Route))
const NavigationLazyRoute = NavigationLazyRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/navigation.lazy').then((d) => d.Route))
const Layout1LazyRoute = Layout1LazyRouteImport.update({
  id: '/layout1',
  path: '/layout1',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/layout1.lazy').then((d) => d.Route))
const IndexPageLazyRoute = IndexPageLazyRouteImport.update({
  id: '/index-page',
  path: '/index-page',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index-page.lazy').then((d) => d.Route))
const Flow2LazyRoute = Flow2LazyRouteImport.update({
  id: '/flow2',
  path: '/flow2',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/flow2.lazy').then((d) => d.Route))
const Flow1LazyRoute = Flow1LazyRouteImport.update({
  id: '/flow1',
  path: '/flow1',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/flow1.lazy').then((d) => d.Route))
const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/flow1': typeof Flow1LazyRoute
  '/flow2': typeof Flow2LazyRoute
  '/index-page': typeof IndexPageLazyRoute
  '/layout1': typeof Layout1LazyRoute
  '/navigation': typeof NavigationLazyRoute
  '/overflow': typeof OverflowLazyRoute
  '/raw-html-with-css': typeof RawHtmlWithCssLazyRoute
  '/ref-example': typeof RefExampleLazyRoute
  '/test': typeof TestLazyRoute
  '/test-compose-refs': typeof TestComposeRefsLazyRoute
  '/test-form': typeof TestFormLazyRoute
  '/test-primitive': typeof TestPrimitiveLazyRoute
  '/test-slot': typeof TestSlotLazyRoute
  '/test-state-machine': typeof TestStateMachineLazyRoute
  '/test-toggle': typeof TestToggleLazyRoute
  '/upgrade-form': typeof UpgradeFormLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/flow1': typeof Flow1LazyRoute
  '/flow2': typeof Flow2LazyRoute
  '/index-page': typeof IndexPageLazyRoute
  '/layout1': typeof Layout1LazyRoute
  '/navigation': typeof NavigationLazyRoute
  '/overflow': typeof OverflowLazyRoute
  '/raw-html-with-css': typeof RawHtmlWithCssLazyRoute
  '/ref-example': typeof RefExampleLazyRoute
  '/test': typeof TestLazyRoute
  '/test-compose-refs': typeof TestComposeRefsLazyRoute
  '/test-form': typeof TestFormLazyRoute
  '/test-primitive': typeof TestPrimitiveLazyRoute
  '/test-slot': typeof TestSlotLazyRoute
  '/test-state-machine': typeof TestStateMachineLazyRoute
  '/test-toggle': typeof TestToggleLazyRoute
  '/upgrade-form': typeof UpgradeFormLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/flow1': typeof Flow1LazyRoute
  '/flow2': typeof Flow2LazyRoute
  '/index-page': typeof IndexPageLazyRoute
  '/layout1': typeof Layout1LazyRoute
  '/navigation': typeof NavigationLazyRoute
  '/overflow': typeof OverflowLazyRoute
  '/raw-html-with-css': typeof RawHtmlWithCssLazyRoute
  '/ref-example': typeof RefExampleLazyRoute
  '/test': typeof TestLazyRoute
  '/test-compose-refs': typeof TestComposeRefsLazyRoute
  '/test-form': typeof TestFormLazyRoute
  '/test-primitive': typeof TestPrimitiveLazyRoute
  '/test-slot': typeof TestSlotLazyRoute
  '/test-state-machine': typeof TestStateMachineLazyRoute
  '/test-toggle': typeof TestToggleLazyRoute
  '/upgrade-form': typeof UpgradeFormLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/flow1'
    | '/flow2'
    | '/index-page'
    | '/layout1'
    | '/navigation'
    | '/overflow'
    | '/raw-html-with-css'
    | '/ref-example'
    | '/test'
    | '/test-compose-refs'
    | '/test-form'
    | '/test-primitive'
    | '/test-slot'
    | '/test-state-machine'
    | '/test-toggle'
    | '/upgrade-form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/flow1'
    | '/flow2'
    | '/index-page'
    | '/layout1'
    | '/navigation'
    | '/overflow'
    | '/raw-html-with-css'
    | '/ref-example'
    | '/test'
    | '/test-compose-refs'
    | '/test-form'
    | '/test-primitive'
    | '/test-slot'
    | '/test-state-machine'
    | '/test-toggle'
    | '/upgrade-form'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/flow1'
    | '/flow2'
    | '/index-page'
    | '/layout1'
    | '/navigation'
    | '/overflow'
    | '/raw-html-with-css'
    | '/ref-example'
    | '/test'
    | '/test-compose-refs'
    | '/test-form'
    | '/test-primitive'
    | '/test-slot'
    | '/test-state-machine'
    | '/test-toggle'
    | '/upgrade-form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutLazyRoute: typeof AboutLazyRoute
  Flow1LazyRoute: typeof Flow1LazyRoute
  Flow2LazyRoute: typeof Flow2LazyRoute
  IndexPageLazyRoute: typeof IndexPageLazyRoute
  Layout1LazyRoute: typeof Layout1LazyRoute
  NavigationLazyRoute: typeof NavigationLazyRoute
  OverflowLazyRoute: typeof OverflowLazyRoute
  RawHtmlWithCssLazyRoute: typeof RawHtmlWithCssLazyRoute
  RefExampleLazyRoute: typeof RefExampleLazyRoute
  TestLazyRoute: typeof TestLazyRoute
  TestComposeRefsLazyRoute: typeof TestComposeRefsLazyRoute
  TestFormLazyRoute: typeof TestFormLazyRoute
  TestPrimitiveLazyRoute: typeof TestPrimitiveLazyRoute
  TestSlotLazyRoute: typeof TestSlotLazyRoute
  TestStateMachineLazyRoute: typeof TestStateMachineLazyRoute
  TestToggleLazyRoute: typeof TestToggleLazyRoute
  UpgradeFormLazyRoute: typeof UpgradeFormLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade-form': {
      id: '/upgrade-form'
      path: '/upgrade-form'
      fullPath: '/upgrade-form'
      preLoaderRoute: typeof UpgradeFormLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-toggle': {
      id: '/test-toggle'
      path: '/test-toggle'
      fullPath: '/test-toggle'
      preLoaderRoute: typeof TestToggleLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-state-machine': {
      id: '/test-state-machine'
      path: '/test-state-machine'
      fullPath: '/test-state-machine'
      preLoaderRoute: typeof TestStateMachineLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-slot': {
      id: '/test-slot'
      path: '/test-slot'
      fullPath: '/test-slot'
      preLoaderRoute: typeof TestSlotLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-primitive': {
      id: '/test-primitive'
      path: '/test-primitive'
      fullPath: '/test-primitive'
      preLoaderRoute: typeof TestPrimitiveLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-form': {
      id: '/test-form'
      path: '/test-form'
      fullPath: '/test-form'
      preLoaderRoute: typeof TestFormLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-compose-refs': {
      id: '/test-compose-refs'
      path: '/test-compose-refs'
      fullPath: '/test-compose-refs'
      preLoaderRoute: typeof TestComposeRefsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ref-example': {
      id: '/ref-example'
      path: '/ref-example'
      fullPath: '/ref-example'
      preLoaderRoute: typeof RefExampleLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw-html-with-css': {
      id: '/raw-html-with-css'
      path: '/raw-html-with-css'
      fullPath: '/raw-html-with-css'
      preLoaderRoute: typeof RawHtmlWithCssLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overflow': {
      id: '/overflow'
      path: '/overflow'
      fullPath: '/overflow'
      preLoaderRoute: typeof OverflowLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout1': {
      id: '/layout1'
      path: '/layout1'
      fullPath: '/layout1'
      preLoaderRoute: typeof Layout1LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index-page': {
      id: '/index-page'
      path: '/index-page'
      fullPath: '/index-page'
      preLoaderRoute: typeof IndexPageLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow2': {
      id: '/flow2'
      path: '/flow2'
      fullPath: '/flow2'
      preLoaderRoute: typeof Flow2LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow1': {
      id: '/flow1'
      path: '/flow1'
      fullPath: '/flow1'
      preLoaderRoute: typeof Flow1LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutLazyRoute: AboutLazyRoute,
  Flow1LazyRoute: Flow1LazyRoute,
  Flow2LazyRoute: Flow2LazyRoute,
  IndexPageLazyRoute: IndexPageLazyRoute,
  Layout1LazyRoute: Layout1LazyRoute,
  NavigationLazyRoute: NavigationLazyRoute,
  OverflowLazyRoute: OverflowLazyRoute,
  RawHtmlWithCssLazyRoute: RawHtmlWithCssLazyRoute,
  RefExampleLazyRoute: RefExampleLazyRoute,
  TestLazyRoute: TestLazyRoute,
  TestComposeRefsLazyRoute: TestComposeRefsLazyRoute,
  TestFormLazyRoute: TestFormLazyRoute,
  TestPrimitiveLazyRoute: TestPrimitiveLazyRoute,
  TestSlotLazyRoute: TestSlotLazyRoute,
  TestStateMachineLazyRoute: TestStateMachineLazyRoute,
  TestToggleLazyRoute: TestToggleLazyRoute,
  UpgradeFormLazyRoute: UpgradeFormLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
